In [74]:
import string 
import math
import numpy as np 
import pandas as pd 
pd.set_option('display.max_columns', 100) 
pd.set_option('display.max_rows', 10) 
pd.set_option('display.width', 1000) 
from itertools import cycle 
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
import sklearn
import datetime
from datetime import datetime
from sklearn.model_selection import train_test_split

In [15]:
df=pd.read_csv(r'E:\gender\gender_made.csv')

In [20]:
df # 'nose_wide', 'nose_long', 'lips_thin', 'distance_nose_to_lip_long', 'long_hair'

      Unnamed: 0  index  long_hair  forehead_width_cm  forehead_height_cm  forehead_width_mm  forehead_width_conventional_units  nose_wide  nose_long  lips_thin  distance_nose_to_lip_long  gender
0            0.0      0        1.0               11.8                 6.1                118                           0.025806        1.0        0.0        1.0                        1.0     NaN
1            1.0      1        0.0               14.0                 5.4                140                           0.167742        0.0        0.0        1.0                        0.0     NaN
2            2.0      2        0.0               11.8                 6.3                118                           0.025806        1.0        1.0        1.0                        1.0     NaN
3            3.0      3        0.0               14.4                 6.1                144                           0.193548        0.0        1.0        1.0                        1.0     NaN
4            4.0      4        1.0               13.5                 5.9                135                           0.135484        0.0        0.0        0.0                        0.0     NaN
...          ...    ...        ...                ...                 ...                ...                                ...        ...        ...        ...                        ...     ...
4996         NaN   4996        1.0               13.6                 5.1                136                           0.141935        0.0        0.0        0.0                        0.0  Female
4997         NaN   4997        1.0               11.9                 5.4                119                           0.032258        0.0        0.0        0.0                        0.0  Female
4998         NaN   4998        1.0               12.9                 5.7                129                           0.096774        0.0        0.0        0.0                        0.0  Female
4999         NaN   4999        1.0               13.2                 6.2                132                           0.116129        0.0        0.0        0.0                        0.0  Female
5000         NaN   5000        1.0               15.4                 5.4                154                           0.258065        1.0        1.0        1.0                        1.0    Male

[5001 rows x 12 columns]

In [21]:
df_test=df[0:1001] #test

In [35]:
df_test

      index  long_hair  forehead_width_cm  forehead_height_cm  forehead_width_mm  forehead_width_conventional_units  nose_wide  nose_long  lips_thin  distance_nose_to_lip_long gender
0         0        1.0               11.8                 6.1                118                           0.025806        1.0        0.0        1.0                        1.0    NaN
1         1        0.0               14.0                 5.4                140                           0.167742        0.0        0.0        1.0                        0.0    NaN
2         2        0.0               11.8                 6.3                118                           0.025806        1.0        1.0        1.0                        1.0    NaN
3         3        0.0               14.4                 6.1                144                           0.193548        0.0        1.0        1.0                        1.0    NaN
4         4        1.0               13.5                 5.9                135                           0.135484        0.0        0.0        0.0                        0.0    NaN
...     ...        ...                ...                 ...                ...                                ...        ...        ...        ...                        ...    ...
996     996        0.0               12.7                 6.0                127                           0.083871        0.0        0.0        0.0                        1.0    NaN
997     997        1.0               14.1                 5.3                141                           0.174194        0.0        0.0        0.0                        0.0    NaN
998     998        1.0               12.1                 6.2                121                           0.045161        1.0        1.0        1.0                        0.0    NaN
999     999        1.0               14.9                 6.0                149                           0.225806        1.0        1.0        1.0                        1.0    NaN
1000   1000        1.0               14.2                 5.7                142                           0.180645        1.0        1.0        1.0                        1.0    NaN

[1001 rows x 11 columns]

In [27]:
df_train=df[1001:5001].reset_index(drop=True)

In [38]:
def gender_num(gend):
    if (gend=='Male'):
        return 1
    else:
        return 0

In [100]:
def gender_str(gend):
    if (gend==1):
        return "Male"
    else:
        return "Female"

In [103]:
gender_str(0)

'Female'

In [45]:
df_train

      index  long_hair  forehead_width_cm  forehead_height_cm  forehead_width_mm  forehead_width_conventional_units  nose_wide  nose_long  lips_thin  distance_nose_to_lip_long  gender
0      1001        1.0               13.4                 6.1                134                           0.129032        1.0        1.0        1.0                        1.0       1
1      1002        0.0               13.5                 6.4                135                           0.135484        1.0        1.0        1.0                        1.0       1
2      1003        1.0               13.4                 5.4                134                           0.129032        1.0        0.0        0.0                        0.0       0
3      1004        1.0               14.1                 6.3                141                           0.174194        0.0        0.0        0.0                        0.0       0
4      1005        1.0               12.5                 5.2                125                           0.070968        0.0        0.0        0.0                        0.0       0
...     ...        ...                ...                 ...                ...                                ...        ...        ...        ...                        ...     ...
3995   4996        1.0               13.6                 5.1                136                           0.141935        0.0        0.0        0.0                        0.0       0
3996   4997        1.0               11.9                 5.4                119                           0.032258        0.0        0.0        0.0                        0.0       0
3997   4998        1.0               12.9                 5.7                129                           0.096774        0.0        0.0        0.0                        0.0       0
3998   4999        1.0               13.2                 6.2                132                           0.116129        0.0        0.0        0.0                        0.0       0
3999   5000        1.0               15.4                 5.4                154                           0.258065        1.0        1.0        1.0                        1.0       1

[4000 rows x 11 columns]

In [44]:
df_train['gender']=list(map(gender_num,df_train['gender']))

In [18]:
features=['nose_wide', 'nose_long', 'lips_thin', 'distance_nose_to_lip_long', 'long_hair']
for i in range(len(features)):
    for j in range(df["index"].size):
        df[features[i]][j]=round(df[features[i]][j])

<ipython-input-18-107b5f04a4f8>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[features[i]][j]=round(df[features[i]][j])

In [53]:
X=df_train.columns.values.tolist()
X.remove('gender')
X=df_train[X]
y=df_train['gender']

In [66]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state =0)

In [70]:
X_test=X_test.reset_index(drop=True)

In [88]:
count=5
acc=[0]*count
for depth in range(count):
    regr = RandomForestClassifier(n_estimators=1*(depth+1), random_state=5)
    regr.fit(X_train,y_train)
    y_pred=regr.predict(X_test)
    for i in range(len(y_pred)):
        if(y_pred[i]==y_test[i]):
            acc[depth]+=1
    acc[depth]/=len(y_pred)

In [89]:
acc

[0.9625, 0.96875, 0.97375, 0.97625, 0.975]

In [82]:
y_test.value_counts()

0    408
1    392
Name: gender, dtype: int64

In [85]:
regr = RandomForestClassifier(n_estimators=10, random_state=0)
regr.fit(X_train,y_train)

RandomForestClassifier(n_estimators=10, random_state=0)

In [92]:
X=df_test.columns.values.tolist()
X.remove('gender')
df_test=df_test[X]

In [93]:
y_pred=regr.predict(df_test)

In [99]:
males=0
for i in range(len(y_pred)):
    if (y_pred[i]==1):
        males+=1
males

496

In [104]:
res=list(map(gender_str,y_pred))
res

['Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Female',
 'Male',
 'Male',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Female',
 'Female',
 'Female',
 'Female',
 'Male',
 'Male',
 ...]

In [105]:
save = pd.DataFrame(res, columns=["colummn"])
save.to_csv('genders.csv', index=False)